import { prepareEntry } from "@/lib/entries";
import type { GlossaryEntry } from "@/lib/types";

const sampleUser = "seed-editor";

export const sampleEntries: GlossaryEntry[] = [
  prepareEntry({
    id: "1",
    headword_pinyin: "Mòjīng",
    headword_characters: "墨經",
    heading_rich_text: "Mòjīng 墨經",
    sort_key: "mojing",
    english_gloss_or_translation: "Mohist Canons",
    entry_type: "text",
    body_rich_text: "<p>The Mòjīng is significant for discussions of inference, language, and standards.</p>",
    status: "final",
    tags: ["Mohism", "canon"],
    related_entries: [{ id: "4", relationship: "commentary-on" }],
    created_by: sampleUser,
    updated_by: sampleUser
  }),
  prepareEntry({
    id: "2",
    headword_pinyin: "Shěn Yǒudǐng",
    headword_characters: "沈有鼎",
    heading_rich_text: "Shěn Yǒudǐng 沈有鼎",
    sort_key: "shen youding",
    english_gloss_or_translation: "Shen Youding",
    entry_type: "person",
    body_rich_text: "<p>Shěn Yǒudǐng is notable for modern studies of Chinese logic and textual interpretation.</p>",
    status: "reviewed",
    tags: ["modern scholarship"],
    related_entries: [],
    created_by: sampleUser,
    updated_by: sampleUser
  }),
  prepareEntry({
    id: "3",
    headword_pinyin: "Mòzǐ jiāngǔ",
    headword_characters: "墨子閒詁",
    heading_rich_text: "Mòzǐ jiāngǔ 墨子閒詁",
    sort_key: "mozi jiangu",
    english_gloss_or_translation: "Annotated Glosses on the Mozi",
    entry_type: "text",
    body_rich_text: "<p>This commentary is important for reconstructing difficult passages and editorial choices.</p>",
    status: "reviewed",
    tags: ["commentary"],
    related_entries: [{ id: "1", relationship: "comments-on" }],
    created_by: sampleUser,
    updated_by: sampleUser
  }),
  prepareEntry({
    id: "4",
    headword_pinyin: "yǐn shuō jiù jīng",
    headword_characters: "引說就經",
    heading_rich_text: "yǐn shuō jiù jīng 引說就經",
    sort_key: "yin shuo jiu jing",
    english_gloss_or_translation: "Using explanations to settle the canon",
    entry_type: "concept",
    body_rich_text: "<p>The phrase is relevant because it captures a method for relating explanatory material to canonical wording.</p>",
    status: "draft",
    tags: ["hermeneutics"],
    related_entries: [{ id: "1", relationship: "appears-in" }],
    created_by: sampleUser,
    updated_by: sampleUser
  }),
  prepareEntry({
    id: "5",
    headword_pinyin: "biàn",
    headword_characters: "辯",
    heading_rich_text: "biàn 辯",
    sort_key: "bian",
    english_gloss_or_translation: "disputation; discrimination",
    entry_type: "concept",
    body_rich_text: "<p>Biàn is significant in debates about naming, argument, and classification.</p>",
    status: "final",
    tags: ["terminology"],
    related_entries: [],
    created_by: sampleUser,
    updated_by: sampleUser
  }),
  prepareEntry({
    id: "6",
    headword_pinyin: "Gōngsūn Lóng",
    headword_characters: "公孫龍",
    heading_rich_text: "Gōngsūn Lóng 公孫龍",
    sort_key: "gongsun long",
    english_gloss_or_translation: "Gongsun Long",
    entry_type: "person",
    body_rich_text: "<p>Gōngsūn Lóng remains notable because his arguments shape later discussions of reference.</p>",
    status: "final",
    tags: ["Warring States"],
    related_entries: [],
    created_by: sampleUser,
    updated_by: sampleUser
  }),
  prepareEntry({
    id: "7",
    headword_pinyin: "míng",
    headword_characters: "名",
    heading_rich_text: "míng 名",
    sort_key: "ming",
    english_gloss_or_translation: "name",
    entry_type: "concept",
    body_rich_text: "<p>Míng is important in accounts of language, naming, and semantic fit.</p>",
    status: "reviewed",
    tags: ["language"],
    related_entries: [],
    created_by: sampleUser,
    updated_by: sampleUser
  }),
  prepareEntry({
    id: "8",
    headword_pinyin: "Míngjiā",
    headword_characters: "名家",
    heading_rich_text: "Míngjiā 名家",
    sort_key: "mingjia",
    english_gloss_or_translation: "School of Names",
    entry_type: "school",
    body_rich_text: "<p>The category is significant in later historiography of disputation and logic.</p>",
    status: "draft",
    tags: ["school"],
    related_entries: [{ id: "6", relationship: "associated-with" }],
    created_by: sampleUser,
    updated_by: sampleUser
  }),
  prepareEntry({
    id: "9",
    headword_pinyin: "fǎ",
    headword_characters: "法",
    heading_rich_text: "fǎ 法",
    sort_key: "fa",
    english_gloss_or_translation: "model; standard",
    entry_type: "concept",
    body_rich_text: "<p>Fǎ is relevant because it anchors Mohist discussions of standards and analogy.</p>",
    status: "final",
    tags: ["Mohism"],
    related_entries: [],
    created_by: sampleUser,
    updated_by: sampleUser
  })
];
